### ISSUE TITLE
`VerifyFunction` parameters are passed in the wrong order

### ISSUE THREAD

**Issue by NilsSutter** [JMPerez/passport-spotify#104]
Hey everyone, I was trying to setup an express-api where users would always authorize and authenticate via spotify, for this I wanted to use `passport-spotify`.

I'm also using typescript and a mongoDB. From the documentation, this was the setup to use the `SpotifyStrategy`:
```
passport.use(
  new SpotifyStrategy(
    {
      clientID: client_id,
      clientSecret: client_secret,
      callbackURL: 'http://localhost:8888/auth/spotify/callback',
    },
    function (accessToken, refreshToken, expires_in, profile, done) {
      User.findOrCreate({spotifyId: profile.id}, function (err, user) {
        return done(err, user);
      });
    }
  )
);
```

**Problem**
However, the arguments seem to be passed in in the wrong order, at least the typescript compiler will complain about it, i.e.

<img width="947" alt="Screenshot 2021-04-11 at 13 36 30" src="https://user-images.githubusercontent.com/48183520/114302815-0d78ef00-9acb-11eb-8e0a-23a5ceb7e331.png">

Therefore, it seems to be that the right order of function parameters for the `VerifyFunction` should be as followed:
`async(_req, accessToken, refreshToken, profile, done, expires_in) => {...}`

However, when this is being done, I will get the following mongoose validation errors :
```
{ Error: User validation failed: spotifyId: Path `spotifyId` is required., userName: Path `userName` is required.
    at ValidationError.inspect (/Users/nilssutter/Desktop/spotify_swipes/node_modules/mongoose/lib/error/validation.js:47:26)
    at formatValue (internal/util/inspect.js:522:31)
    at inspect (internal/util/inspect.js:197:10)
    at formatWithOptions (internal/util/inspect.js:1390:12)
    at Console.(anonymous function) (internal/console/constructor.js:277:10)
    at Console.log (internal/console/constructor.js:287:61)
    at Function.UserRepository.findAndUpdateOrCreate
```

The reason for this is that `profile` is still undefined.

**Workaround**
It might be that I'm messing something up, but my current workaround is smart-casting the parameter to the type they actually should have, i.e.:

<img width="1297" alt="Screenshot 2021-04-11 at 13 45 06" src="https://user-images.githubusercontent.com/48183520/114303034-2df57900-9acc-11eb-8a59-38978ad84637.png">

So yeah, I'm a bit confused :D

This currently works well for me but I suppose the arguments for the `VerifyFunction` should come in in another order in the first place?

**Comment by alexstaroselsky** [comment]
I think the issue is that [@types/passport-spotify](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport-spotify/index.d.ts) specifies the wrong order for the [arguments](https://github.com/JMPerez/passport-spotify/blob/master/lib/passport-spotify/strategy.js#L88). I'm going to create an MR to add types to the library. That is the [recommended approach](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) for libraries these days.

**Comment by NilsSutter** [comment]
Hey @alexstaroselsky . Thanks for pointing this out :)

**Comment by alexstaroselsky** [comment]
I created a PR for [@types/passport-spotify](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52762). Once that is approved/merged at least that issue for the verity function signature should be resolved. That being said, you still would likely need to use type casting or similar for `passport.authenticate` as `showDialog` (if you are using that) is not supported by [AuthenticateOptions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport/index.d.ts#L52)

**Comment by LarissaGuder** [comment]
> I created a PR for [@types/passport-spotify](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52762). Once that is approved/merged at least that issue for the verity function signature should be resolved. That being said, you still would likely need to use type casting or similar for `passport.authenticate` as `showDialog` (if you are using that) is not supported by [AuthenticateOptions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport/index.d.ts#L52)

Hi! Your PR didnt pass.
