### ISSUE TITLE
Error when bundling with Webpack

### ISSUE THREAD

**Issue by emyann** [JMPerez/passport-spotify#83]
Hello, thank you for this passport! 

I have a NodeJs and TypeScript server I bundle using webpack with target as `node`. When I'm using this package I have this exception thrown at build time:

```sh
throw new Error('Could not find package.json up from ' +
^

Error: Could not find package.json up from 1164
    at Function.pkginfo.find (/Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:214015:11)
    at Function.pkginfo.read (/Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:214042:22)
    at module.exports (/Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:213988:21)
    at Object.<anonymous> (/Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:214049:1)
    at Object.webpackEmptyContext.keys (/Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:214055:30)
    at __webpack_require__ (/Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:30:30)
    at Object.<anonymous> (/Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:110086:1)
    at Object.Op (/Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:110093:30)
    at __webpack_require__ (/Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:30:30)
    at Module.<anonymous> (/Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:215348:24)
    at __webpack_require__ (/Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:30:30)
    at /Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:94:18
    at /Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:97:10
    at webpackUniversalModuleDefinition (/Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:3:20)
    at Object.<anonymous> (/Users/yrenaudin/Documents/Projects/profilr-api/dist/index.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

I dug a bit the issue and it seems to originate from the usage of `pkgInfo`, did someone already stumble upon this ?

**Comment by JMPerez** [comment]
This should be fixed by https://github.com/JMPerez/passport-spotify/pull/86
